// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: api/proto/service/service.proto

package service_2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GoYandexGophkeeper_Register_FullMethodName        = "/service_2.GoYandexGophkeeper/Register"
	GoYandexGophkeeper_Login_FullMethodName           = "/service_2.GoYandexGophkeeper/Login"
	GoYandexGophkeeper_CreateData_FullMethodName      = "/service_2.GoYandexGophkeeper/CreateData"
	GoYandexGophkeeper_GetDataBatch_FullMethodName    = "/service_2.GoYandexGophkeeper/GetDataBatch"
	GoYandexGophkeeper_UpdateData_FullMethodName      = "/service_2.GoYandexGophkeeper/UpdateData"
	GoYandexGophkeeper_DeleteData_FullMethodName      = "/service_2.GoYandexGophkeeper/DeleteData"
	GoYandexGophkeeper_CreateDataChunk_FullMethodName = "/service_2.GoYandexGophkeeper/CreateDataChunk"
	GoYandexGophkeeper_GetDataChunk_FullMethodName    = "/service_2.GoYandexGophkeeper/GetDataChunk"
	GoYandexGophkeeper_UpdateDataChunk_FullMethodName = "/service_2.GoYandexGophkeeper/UpdateDataChunk"
)

// GoYandexGophkeeperClient is the client API for GoYandexGophkeeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoYandexGophkeeperClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	CreateData(ctx context.Context, in *CreateDataRequest, opts ...grpc.CallOption) (*CreateDataResponse, error)
	GetDataBatch(ctx context.Context, in *GetDataBatchRequest, opts ...grpc.CallOption) (*GetDataBatchResponse, error)
	UpdateData(ctx context.Context, in *UpdateDataRequest, opts ...grpc.CallOption) (*UpdateDataResponse, error)
	DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error)
	CreateDataChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateDataChunkRequest, CreateDataChunkResponse], error)
	GetDataChunk(ctx context.Context, in *GetDataChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDataChunkResponse], error)
	UpdateDataChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateDataChunkRequest, UpdateDataChunkResponse], error)
}

type goYandexGophkeeperClient struct {
	cc grpc.ClientConnInterface
}

func NewGoYandexGophkeeperClient(cc grpc.ClientConnInterface) GoYandexGophkeeperClient {
	return &goYandexGophkeeperClient{cc}
}

func (c *goYandexGophkeeperClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, GoYandexGophkeeper_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goYandexGophkeeperClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, GoYandexGophkeeper_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goYandexGophkeeperClient) CreateData(ctx context.Context, in *CreateDataRequest, opts ...grpc.CallOption) (*CreateDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDataResponse)
	err := c.cc.Invoke(ctx, GoYandexGophkeeper_CreateData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goYandexGophkeeperClient) GetDataBatch(ctx context.Context, in *GetDataBatchRequest, opts ...grpc.CallOption) (*GetDataBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataBatchResponse)
	err := c.cc.Invoke(ctx, GoYandexGophkeeper_GetDataBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goYandexGophkeeperClient) UpdateData(ctx context.Context, in *UpdateDataRequest, opts ...grpc.CallOption) (*UpdateDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDataResponse)
	err := c.cc.Invoke(ctx, GoYandexGophkeeper_UpdateData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goYandexGophkeeperClient) DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDataResponse)
	err := c.cc.Invoke(ctx, GoYandexGophkeeper_DeleteData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goYandexGophkeeperClient) CreateDataChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateDataChunkRequest, CreateDataChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoYandexGophkeeper_ServiceDesc.Streams[0], GoYandexGophkeeper_CreateDataChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateDataChunkRequest, CreateDataChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoYandexGophkeeper_CreateDataChunkClient = grpc.ClientStreamingClient[CreateDataChunkRequest, CreateDataChunkResponse]

func (c *goYandexGophkeeperClient) GetDataChunk(ctx context.Context, in *GetDataChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetDataChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoYandexGophkeeper_ServiceDesc.Streams[1], GoYandexGophkeeper_GetDataChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDataChunkRequest, GetDataChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoYandexGophkeeper_GetDataChunkClient = grpc.ServerStreamingClient[GetDataChunkResponse]

func (c *goYandexGophkeeperClient) UpdateDataChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateDataChunkRequest, UpdateDataChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GoYandexGophkeeper_ServiceDesc.Streams[2], GoYandexGophkeeper_UpdateDataChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateDataChunkRequest, UpdateDataChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoYandexGophkeeper_UpdateDataChunkClient = grpc.ClientStreamingClient[UpdateDataChunkRequest, UpdateDataChunkResponse]

// GoYandexGophkeeperServer is the server API for GoYandexGophkeeper service.
// All implementations must embed UnimplementedGoYandexGophkeeperServer
// for forward compatibility.
type GoYandexGophkeeperServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	CreateData(context.Context, *CreateDataRequest) (*CreateDataResponse, error)
	GetDataBatch(context.Context, *GetDataBatchRequest) (*GetDataBatchResponse, error)
	UpdateData(context.Context, *UpdateDataRequest) (*UpdateDataResponse, error)
	DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error)
	CreateDataChunk(grpc.ClientStreamingServer[CreateDataChunkRequest, CreateDataChunkResponse]) error
	GetDataChunk(*GetDataChunkRequest, grpc.ServerStreamingServer[GetDataChunkResponse]) error
	UpdateDataChunk(grpc.ClientStreamingServer[UpdateDataChunkRequest, UpdateDataChunkResponse]) error
	mustEmbedUnimplementedGoYandexGophkeeperServer()
}

// UnimplementedGoYandexGophkeeperServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoYandexGophkeeperServer struct{}

func (UnimplementedGoYandexGophkeeperServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGoYandexGophkeeperServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGoYandexGophkeeperServer) CreateData(context.Context, *CreateDataRequest) (*CreateDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateData not implemented")
}
func (UnimplementedGoYandexGophkeeperServer) GetDataBatch(context.Context, *GetDataBatchRequest) (*GetDataBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataBatch not implemented")
}
func (UnimplementedGoYandexGophkeeperServer) UpdateData(context.Context, *UpdateDataRequest) (*UpdateDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateData not implemented")
}
func (UnimplementedGoYandexGophkeeperServer) DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteData not implemented")
}
func (UnimplementedGoYandexGophkeeperServer) CreateDataChunk(grpc.ClientStreamingServer[CreateDataChunkRequest, CreateDataChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CreateDataChunk not implemented")
}
func (UnimplementedGoYandexGophkeeperServer) GetDataChunk(*GetDataChunkRequest, grpc.ServerStreamingServer[GetDataChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetDataChunk not implemented")
}
func (UnimplementedGoYandexGophkeeperServer) UpdateDataChunk(grpc.ClientStreamingServer[UpdateDataChunkRequest, UpdateDataChunkResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UpdateDataChunk not implemented")
}
func (UnimplementedGoYandexGophkeeperServer) mustEmbedUnimplementedGoYandexGophkeeperServer() {}
func (UnimplementedGoYandexGophkeeperServer) testEmbeddedByValue()                            {}

// UnsafeGoYandexGophkeeperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoYandexGophkeeperServer will
// result in compilation errors.
type UnsafeGoYandexGophkeeperServer interface {
	mustEmbedUnimplementedGoYandexGophkeeperServer()
}

func RegisterGoYandexGophkeeperServer(s grpc.ServiceRegistrar, srv GoYandexGophkeeperServer) {
	// If the following call pancis, it indicates UnimplementedGoYandexGophkeeperServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GoYandexGophkeeper_ServiceDesc, srv)
}

func _GoYandexGophkeeper_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoYandexGophkeeperServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoYandexGophkeeper_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoYandexGophkeeperServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoYandexGophkeeper_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoYandexGophkeeperServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoYandexGophkeeper_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoYandexGophkeeperServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoYandexGophkeeper_CreateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoYandexGophkeeperServer).CreateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoYandexGophkeeper_CreateData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoYandexGophkeeperServer).CreateData(ctx, req.(*CreateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoYandexGophkeeper_GetDataBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoYandexGophkeeperServer).GetDataBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoYandexGophkeeper_GetDataBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoYandexGophkeeperServer).GetDataBatch(ctx, req.(*GetDataBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoYandexGophkeeper_UpdateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoYandexGophkeeperServer).UpdateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoYandexGophkeeper_UpdateData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoYandexGophkeeperServer).UpdateData(ctx, req.(*UpdateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoYandexGophkeeper_DeleteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoYandexGophkeeperServer).DeleteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoYandexGophkeeper_DeleteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoYandexGophkeeperServer).DeleteData(ctx, req.(*DeleteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoYandexGophkeeper_CreateDataChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GoYandexGophkeeperServer).CreateDataChunk(&grpc.GenericServerStream[CreateDataChunkRequest, CreateDataChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoYandexGophkeeper_CreateDataChunkServer = grpc.ClientStreamingServer[CreateDataChunkRequest, CreateDataChunkResponse]

func _GoYandexGophkeeper_GetDataChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetDataChunkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoYandexGophkeeperServer).GetDataChunk(m, &grpc.GenericServerStream[GetDataChunkRequest, GetDataChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoYandexGophkeeper_GetDataChunkServer = grpc.ServerStreamingServer[GetDataChunkResponse]

func _GoYandexGophkeeper_UpdateDataChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GoYandexGophkeeperServer).UpdateDataChunk(&grpc.GenericServerStream[UpdateDataChunkRequest, UpdateDataChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GoYandexGophkeeper_UpdateDataChunkServer = grpc.ClientStreamingServer[UpdateDataChunkRequest, UpdateDataChunkResponse]

// GoYandexGophkeeper_ServiceDesc is the grpc.ServiceDesc for GoYandexGophkeeper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoYandexGophkeeper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service_2.GoYandexGophkeeper",
	HandlerType: (*GoYandexGophkeeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _GoYandexGophkeeper_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GoYandexGophkeeper_Login_Handler,
		},
		{
			MethodName: "CreateData",
			Handler:    _GoYandexGophkeeper_CreateData_Handler,
		},
		{
			MethodName: "GetDataBatch",
			Handler:    _GoYandexGophkeeper_GetDataBatch_Handler,
		},
		{
			MethodName: "UpdateData",
			Handler:    _GoYandexGophkeeper_UpdateData_Handler,
		},
		{
			MethodName: "DeleteData",
			Handler:    _GoYandexGophkeeper_DeleteData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateDataChunk",
			Handler:       _GoYandexGophkeeper_CreateDataChunk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetDataChunk",
			Handler:       _GoYandexGophkeeper_GetDataChunk_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateDataChunk",
			Handler:       _GoYandexGophkeeper_UpdateDataChunk_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/service/service.proto",
}
