// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/handler/grpc.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/MisterMaks/go-yandex-gophkeeper/internal/server/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockUsecaseInterface is a mock of UsecaseInterface interface.
type MockUsecaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseInterfaceMockRecorder
}

// MockUsecaseInterfaceMockRecorder is the mock recorder for MockUsecaseInterface.
type MockUsecaseInterfaceMockRecorder struct {
	mock *MockUsecaseInterface
}

// NewMockUsecaseInterface creates a new mock instance.
func NewMockUsecaseInterface(ctrl *gomock.Controller) *MockUsecaseInterface {
	mock := &MockUsecaseInterface{ctrl: ctrl}
	mock.recorder = &MockUsecaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecaseInterface) EXPECT() *MockUsecaseInterfaceMockRecorder {
	return m.recorder
}

// CreateData mocks base method.
func (m *MockUsecaseInterface) CreateData(ctx context.Context, userID, name, dataType string, data []byte) (*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateData", ctx, userID, name, dataType, data)
	ret0, _ := ret[0].(*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateData indicates an expected call of CreateData.
func (mr *MockUsecaseInterfaceMockRecorder) CreateData(ctx, userID, name, dataType, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateData", reflect.TypeOf((*MockUsecaseInterface)(nil).CreateData), ctx, userID, name, dataType, data)
}

// DeleteData mocks base method.
func (m *MockUsecaseInterface) DeleteData(ctx context.Context, userID, id string) (*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteData", ctx, userID, id)
	ret0, _ := ret[0].(*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockUsecaseInterfaceMockRecorder) DeleteData(ctx, userID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockUsecaseInterface)(nil).DeleteData), ctx, userID, id)
}

// GetDataBatch mocks base method.
func (m *MockUsecaseInterface) GetDataBatch(ctx context.Context, userID string) ([]*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataBatch", ctx, userID)
	ret0, _ := ret[0].([]*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataBatch indicates an expected call of GetDataBatch.
func (mr *MockUsecaseInterfaceMockRecorder) GetDataBatch(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataBatch", reflect.TypeOf((*MockUsecaseInterface)(nil).GetDataBatch), ctx, userID)
}

// Login mocks base method.
func (m *MockUsecaseInterface) Login(ctx context.Context, login, password string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, login, password)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUsecaseInterfaceMockRecorder) Login(ctx, login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUsecaseInterface)(nil).Login), ctx, login, password)
}

// Register mocks base method.
func (m *MockUsecaseInterface) Register(ctx context.Context, login, password string, publicKey, privateKeyCipher []byte) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, login, password, publicKey, privateKeyCipher)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUsecaseInterfaceMockRecorder) Register(ctx, login, password, publicKey, privateKeyCipher interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUsecaseInterface)(nil).Register), ctx, login, password, publicKey, privateKeyCipher)
}

// UpdateData mocks base method.
func (m *MockUsecaseInterface) UpdateData(ctx context.Context, userID, id, name, dataType string, data []byte) (*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateData", ctx, userID, id, name, dataType, data)
	ret0, _ := ret[0].(*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateData indicates an expected call of UpdateData.
func (mr *MockUsecaseInterfaceMockRecorder) UpdateData(ctx, userID, id, name, dataType, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateData", reflect.TypeOf((*MockUsecaseInterface)(nil).UpdateData), ctx, userID, id, name, dataType, data)
}
