// Code generated by MockGen. DO NOT EDIT.
// Source: internal/server/usecase/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/MisterMaks/go-yandex-gophkeeper/internal/server/domain"
	gomock "github.com/golang/mock/gomock"
	v7 "github.com/minio/minio-go/v7"
)

// MockPostgresStorageInterface is a mock of PostgresStorageInterface interface.
type MockPostgresStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresStorageInterfaceMockRecorder
}

// MockPostgresStorageInterfaceMockRecorder is the mock recorder for MockPostgresStorageInterface.
type MockPostgresStorageInterfaceMockRecorder struct {
	mock *MockPostgresStorageInterface
}

// NewMockPostgresStorageInterface creates a new mock instance.
func NewMockPostgresStorageInterface(ctrl *gomock.Controller) *MockPostgresStorageInterface {
	mock := &MockPostgresStorageInterface{ctrl: ctrl}
	mock.recorder = &MockPostgresStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresStorageInterface) EXPECT() *MockPostgresStorageInterfaceMockRecorder {
	return m.recorder
}

// AuthUser mocks base method.
func (m *MockPostgresStorageInterface) AuthUser(ctx context.Context, login string, passwordHash []byte) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthUser", ctx, login, passwordHash)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthUser indicates an expected call of AuthUser.
func (mr *MockPostgresStorageInterfaceMockRecorder) AuthUser(ctx, login, passwordHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthUser", reflect.TypeOf((*MockPostgresStorageInterface)(nil).AuthUser), ctx, login, passwordHash)
}

// CreateData mocks base method.
func (m *MockPostgresStorageInterface) CreateData(ctx context.Context, userID, name, dataType string, data []byte) (*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateData", ctx, userID, name, dataType, data)
	ret0, _ := ret[0].(*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateData indicates an expected call of CreateData.
func (mr *MockPostgresStorageInterfaceMockRecorder) CreateData(ctx, userID, name, dataType, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateData", reflect.TypeOf((*MockPostgresStorageInterface)(nil).CreateData), ctx, userID, name, dataType, data)
}

// CreateUser mocks base method.
func (m *MockPostgresStorageInterface) CreateUser(ctx context.Context, login string, passwordHash, publicKey, privateKeyCipher []byte) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, login, passwordHash, publicKey, privateKeyCipher)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockPostgresStorageInterfaceMockRecorder) CreateUser(ctx, login, passwordHash, publicKey, privateKeyCipher interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockPostgresStorageInterface)(nil).CreateUser), ctx, login, passwordHash, publicKey, privateKeyCipher)
}

// DeleteData mocks base method.
func (m *MockPostgresStorageInterface) DeleteData(ctx context.Context, userID, id string) (*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteData", ctx, userID, id)
	ret0, _ := ret[0].(*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteData indicates an expected call of DeleteData.
func (mr *MockPostgresStorageInterfaceMockRecorder) DeleteData(ctx, userID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteData", reflect.TypeOf((*MockPostgresStorageInterface)(nil).DeleteData), ctx, userID, id)
}

// GetData mocks base method.
func (m *MockPostgresStorageInterface) GetData(ctx context.Context, userID, id string) (*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData", ctx, userID, id)
	ret0, _ := ret[0].(*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetData indicates an expected call of GetData.
func (mr *MockPostgresStorageInterfaceMockRecorder) GetData(ctx, userID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockPostgresStorageInterface)(nil).GetData), ctx, userID, id)
}

// GetDataBatch mocks base method.
func (m *MockPostgresStorageInterface) GetDataBatch(ctx context.Context, userID string) ([]*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataBatch", ctx, userID)
	ret0, _ := ret[0].([]*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataBatch indicates an expected call of GetDataBatch.
func (mr *MockPostgresStorageInterfaceMockRecorder) GetDataBatch(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataBatch", reflect.TypeOf((*MockPostgresStorageInterface)(nil).GetDataBatch), ctx, userID)
}

// UpdateData mocks base method.
func (m *MockPostgresStorageInterface) UpdateData(ctx context.Context, userID, id, name, dataType string, data []byte) (*domain.Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateData", ctx, userID, id, name, dataType, data)
	ret0, _ := ret[0].(*domain.Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateData indicates an expected call of UpdateData.
func (mr *MockPostgresStorageInterfaceMockRecorder) UpdateData(ctx, userID, id, name, dataType, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateData", reflect.TypeOf((*MockPostgresStorageInterface)(nil).UpdateData), ctx, userID, id, name, dataType, data)
}

// MockMinioStorageInterface is a mock of MinioStorageInterface interface.
type MockMinioStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMinioStorageInterfaceMockRecorder
}

// MockMinioStorageInterfaceMockRecorder is the mock recorder for MockMinioStorageInterface.
type MockMinioStorageInterfaceMockRecorder struct {
	mock *MockMinioStorageInterface
}

// NewMockMinioStorageInterface creates a new mock instance.
func NewMockMinioStorageInterface(ctrl *gomock.Controller) *MockMinioStorageInterface {
	mock := &MockMinioStorageInterface{ctrl: ctrl}
	mock.recorder = &MockMinioStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMinioStorageInterface) EXPECT() *MockMinioStorageInterfaceMockRecorder {
	return m.recorder
}

// GetObject mocks base method.
func (m *MockMinioStorageInterface) GetObject(ctx context.Context, objectName string) (*v7.Object, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObject", ctx, objectName)
	ret0, _ := ret[0].(*v7.Object)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockMinioStorageInterfaceMockRecorder) GetObject(ctx, objectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockMinioStorageInterface)(nil).GetObject), ctx, objectName)
}

// PutObject mocks base method.
func (m *MockMinioStorageInterface) PutObject(ctx context.Context, objectName string, reader io.Reader, objectSize int64) (v7.UploadInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, objectName, reader, objectSize)
	ret0, _ := ret[0].(v7.UploadInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockMinioStorageInterfaceMockRecorder) PutObject(ctx, objectName, reader, objectSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockMinioStorageInterface)(nil).PutObject), ctx, objectName, reader, objectSize)
}

// RemoveObject mocks base method.
func (m *MockMinioStorageInterface) RemoveObject(ctx context.Context, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveObject", ctx, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveObject indicates an expected call of RemoveObject.
func (mr *MockMinioStorageInterfaceMockRecorder) RemoveObject(ctx, objectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveObject", reflect.TypeOf((*MockMinioStorageInterface)(nil).RemoveObject), ctx, objectName)
}
